### ISSUE TITLE
Copy/Paste adds new line and breaks indentation

### ISSUE THREAD

**Issue by dwarfi09** [aliariff/vscode-erb-beautify#42] opened 2022-12-29 13:16 UTC
In current version I've got a problem with copy/pasting into an erb-file: 
A new-line is added after the first pasted line and the rest of the pasted lines aren't intended at all.

**Comment by dwarfi09** [comment] 2022-12-29 13:41
Just noticed that enabling + disabling `formatOnPaste` in `settings.json` solved the issue:
```
    "[erb]": {
        "editor.defaultFormatter": "aliariff.vscode-erb-beautify",
        "editor.formatOnPaste": false,
    },
```

**Comment by yangjindong** [comment] 2023-02-28 12:31
I have a similar issue. The method doesn't work for me.

**Comment by aliariff** [comment] 2024-02-11 21:49
Closing this since it can't be reproduced, and there's no extra info to go on. 

@yangjindong If the problem persists, please reopen and share more details.

**Closed by aliariff** 2024-02-11 21:49 UTC
