### ISSUE TITLE
Empty file after formatting / save

### ISSUE THREAD

**Issue by p2pow350** [aliariff/vscode-erb-beautify#54] opened 2024-01-22 14:29 UTC
I'm using VSCODE Version: 1.85.2 (Universal) on Mac with latest plugin version.

I don't know how to debug my problem because there are no faulty logs in vscode console, but after saving some erb files I can see that the whole content disappear and I can only get an empty file, and then file is saved empty losing the erb totally.

How can I debug this issue and solve ?
Thanks
Max

**Comment by axelgrubba** [comment] 2024-01-31 10:39
@p2pow350 Facing similar issues. Same happens when using 'Replace All' function in VS Code, where random files get saved as empty losing all the code. Currently I usually disable the extension before doing such operations but obviously it's a bit of a hassle and really prone to error when the extension is enabled and the file gets emptied by mistake and committed to the repo.

**Comment by vassyz** [comment] 2024-02-07 10:14
This has been going on for a while, and I usually just undo the empty file and save again. But this time I ended up committing an empty file. [htmlbeautifier](https://github.com/threedaymonk/htmlbeautifier) hasn't been updated in 2 years, so I don't really have much hope for getting a fix.

**Comment by p2pow350** [comment] 2024-02-07 11:26
> This has been going on for a while, and I usually just undo the empty file and save again. But this time I ended up committing an empty file. [htmlbeautifier](https://github.com/threedaymonk/htmlbeautifier) hasn't been updated in 2 years, so I don't really have much hope for getting a fix.

yes, I'm doing same actions as you or sometimes I'm setting file type as Text so it will not apply format (more or less as  @axelgrubba ). 
I'm undoing and saving file again, but sometimes I need to retry several times before the files will be updated correctly and this is a little bit annoying....another problem is that I haven't found an alternative for formatting ERB 

Btw thanks for you suggestions

**Comment by aliariff** [comment] 2024-02-11 14:02
Hi everyone, 
Could someone please give me a small example of reproducing this issue?

**Comment by vassyz** [comment] 2024-02-11 23:37
@aliariff I can't give you the exact way to reproduce it, because it happens randomly. But the way I can replicate it is to keep saving an `.html.erb` file. On a Mac if you press `cmd + s` from once to fifty times it will happen.

**Comment by namick** [comment] 2024-02-19 16:47
I can verify that this happens occasionally for me as well.  Undo and reformat works around the issue.  I'll continue to watch and see if I can find a pattern.

**Comment by kirley** [comment] 2024-02-28 01:05
I am having the same issue.  It happens for me when there is a change in the file (even a new line space) and then on my mac I hold down Command + S (sometimes i have to hit "S" multiple times while holding down CMD to reproduce it).

**Comment by miharekar** [comment] 2024-05-10 07:43
Seemingly happens more often now. Maybe just my project, but even undoing and re-formatting no longer fixes it. It just keeps deleting all the content.

**Comment by oscarmrom** [comment] 2024-05-15 15:23
This happens on format not necessarily on save it seems. If you have format on save like I did then it may seem that it's on save.

**Comment by oscarmrom** [comment] 2024-05-16 21:01
For some reason the `formattedResult` is empty and therefore clears out our file. I couldn't get it to reproduce consistently either or see it throw any errors but it happens once every 15 tries or so.

https://github.com/aliariff/vscode-erb-beautify/blob/main/src/formatter/htmlbeautifier.ts#L83-L91

I can't pinpoint why it's happening.

For now, by adding a condition in the resolution of the promise it prevents the annoying clearing of the file on format.

```
 if (code) {
                    vscode.window.showErrorMessage(
                        `Failed with exit code: ${code}. '${errorMessage}'`
                    );
                    reject(new Error(`Command failed with exit code ${code}`));
                } else if (formattedResult === '') {
                    reject(new Error(`Formatting returned empty result.`));
                } else {
                    resolve(formattedResult);
                }
```

 I'm going to do this to the extension locally and publish it for my use. Throwing the error is enough of a bandaid for now.

**Comment by aliariff** [comment] 2024-08-31 15:01
Hi everyone,

We have implemented a workaround for this issue by throwing an error message if the formatting output is empty. This approach is similar to the solution mentioned in [this comment](https://github.com/aliariff/vscode-erb-beautify/issues/54#issuecomment-2116170055). Please update your extension to the latest version ([v0.5.0](https://github.com/aliariff/vscode-erb-beautify/releases/tag/v0.5.0)) to apply this workaround.

For now, I am closing this issue. If you can find a reliable way to reproduce the problem, please let me know, and feel free to reopen the issue.

Thank you!

**Closed by aliariff** 2024-08-31 15:01 UTC
