### ISSUE TITLE
Saving on no changes file appear a line of text

### ISSUE THREAD

**Issue by Kyokatarz** [aliariff/vscode-erb-beautify#20] opened 2022-01-04 11:44 UTC
If I save and format on a .erb file with no changes, the following text is appended on top of the file: 

![Screenshot 2022-01-04 at 13 43 46](https://user-images.githubusercontent.com/51933605/148054178-216f2024-03ee-4aef-8dc2-05e5d2534341.png)

**Comment by aliariff** [comment] 2022-01-04 15:50
Hi @Kyokatarz 

Could you give more information from the log.
You can open the developer console from `Help` -> `Toggle Developer Tools`
And while opening the console, try to format your documents, and see what is the output from the console.

it should be something like this or similar:
![image](https://user-images.githubusercontent.com/6806035/148085787-e0127f9b-c6f4-4068-9eb7-fb91d83f814c.png)

**Comment by aliariff** [comment] 2022-12-14 11:33
Close this as no further feedback, assume it is already resolved due to local configuration issue.
Please reopen in case still necessary.

**Closed by aliariff** 2022-12-14 11:33 UTC

**Comment by jclusso** [comment] 2023-07-17 00:44
I have the same problem and I can't reproduce it in my terminal and the console looks like what you posted above @aliariff. I'm struggling to find anything in the linked issue above since I don't have any sort of "verbose" mode configuration enabled that I can find.

**Comment by aliariff** [comment] 2023-07-17 14:11
Hi @jclusso 

Interesting find, unfortunately since last time, I can't really reproduce this issue on my local machine.
For the workaround you mentioned, does it sufficient for you, or its not possible to install the gem on the current project?

**Comment by aliariff** [comment] 2023-07-17 14:34
@jclusso I installed it globally, and no issue as mentioned here.
